### ISSUE TITLE
Works for DM but not for players

### ISSUE THREAD

**Issue by geoidesic** [aka-beer-buddy/fvtt-cycle-token-stack#13]
This is such an essential module, it should be part of core. However, in my game it only seems to work for me, the DM. 
For the players, nothing happens when they try to cycle through. Also when I cycle through it doesn't update for the players.

1. I think this is because the players can't select enemy tokens. So if their own character's token happens to be behind an enemy, then they can't click to cycle.

2. What would be awesome is if when you move a token onto another token it would start out being at the top layer.
It would.

3. It would also be cool if it could be set for the player's view to mirror the DMs – maybe as a player setting for the module.

**Comment by geoidesic** [comment]
I've addressed this with a PR: https://github.com/aka-beer-buddy/fvtt-cycle-token-stack/pulls

**Comment by dmrickey** [comment]
I'm not seeing any changes associated with that PR (I see 3 commits but it looks like they were manually merged instead of using the PR..?). Either way I'm still seeing this issue. The player can only cycle through tokens that they own.
